import { ExampleNavbar, Navbar } from "@/components/Layout/navbar";
import { ExampleSidebar, Sidebar } from "@/components/Layout/sidebar";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import React from "react";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <div className="h-full">
      <SignedIn>
        <main className=" h-full">
          {children}
        </main>
      </SignedIn>
      <SignedOut>
        <ExampleNavbar />

        <div className="hidden md:flex mt-16 h-full w-20 flex-col fixed inset-y-0">
          <ExampleSidebar />
        </div>
        <main className="md:pl-20 pt-16 h-full">
          {children}
        </main>
      </SignedOut>
    </div>
  )
}
export default RootLayout;
